"""
The published tool surface, by name.

This is the contract the era-compatibility checks assert against instead of a
bare count: a count stays green when one tool is dropped and another added, a
name set does not. When a tool is added or removed on purpose, update this
tuple in the same commit — test_manifest_matches_the_registered_tools fails
otherwise.
"""

TOOL_NAMES = (
    "add_assets_to_album",
    "create_album",
    "create_shared_link",
    "create_tag",
    "delete_album",
    "delete_assets",
    "delete_shared_link",
    "delete_tag",
    "empty_trash",
    "export_pdf",
    "get_album",
    "get_album_images",
    "get_album_thumbnails",
    "get_asset_faces",
    "get_asset_image",
    "get_asset_info",
    "get_asset_thumbnail",
    "get_capabilities",
    "get_connection_info",
    "get_duplicates",
    "get_export_preview",
    "get_images_batch",
    "get_map_markers",
    "get_person",
    "get_person_thumbnail",
    "get_server_version",
    "get_shared_link",
    "get_statistics",
    "get_tag",
    "get_thumbnails_batch",
    "get_video_frames",
    "get_video_frames_json",
    "list_albums",
    "list_assets",
    "list_people",
    "list_shared_links",
    "list_tags",
    "merge_people",
    "ping",
    "reassign_face",
    "remove_assets_from_album",
    "resolve_duplicates",
    "restore_assets",
    "restore_trash",
    "revert_asset_edits",
    "rotate_assets",
    "search_explore",
    "search_metadata",
    "search_people",
    "search_smart",
    "tag_assets",
    "untag_assets",
    "update_album",
    "update_asset_metadata",
    "update_credentials",
    "update_person",
    "update_shared_link",
    "update_tag",
    "upload_asset",
)
